// <auto-generated />
using System;
using HRIS_R62.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIS_R62.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250622194007_InitialSchemaByNoKiB")]
    partial class InitialSchemaByNoKiB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmploymentType", b =>
                {
                    b.Property<string>("EmploymentTypeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmploymentTypeID");

                    b.ToTable("EmploymentTypes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceConfiguration", b =>
                {
                    b.Property<string>("AttendanceConfigurationID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("EveningSnacksBreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("EveningSnacksBreakStartTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GraceTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("LunchBreakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("LunchBreakStartTime")
                        .HasColumnType("time");

                    b.HasKey("AttendanceConfigurationID");

                    b.ToTable("AttendanceConfigurations");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceRecord", b =>
                {
                    b.Property<string>("AttendanceRecordID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttendanceConfigurationID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<string>("AttendanceStatusID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("InTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OTEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OTStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OutTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalOvertimeHours")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TotalRegularHours")
                        .HasColumnType("time");

                    b.HasKey("AttendanceRecordID");

                    b.HasIndex("AttendanceConfigurationID");

                    b.HasIndex("AttendanceStatusID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceStatus", b =>
                {
                    b.Property<string>("AttendanceStatusID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttendanceStatusID");

                    b.ToTable("AttendanceStatuss");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Building", b =>
                {
                    b.Property<string>("BuildingID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Company", b =>
                {
                    b.Property<string>("CompanyID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyNameLocal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CompanyID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.DateWiseOfficeTime", b =>
                {
                    b.Property<string>("DateWiseOfficeTimeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("BreakDuration")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ConsideredLunchHour")
                        .HasColumnType("time");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ShiftEndDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShiftStartDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("DateWiseOfficeTimeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("DateWiseOfficeTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Department", b =>
                {
                    b.Property<string>("DepartmentID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentNameLocal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Designation", b =>
                {
                    b.Property<string>("DesignationID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesignationShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DesignationID");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Division", b =>
                {
                    b.Property<string>("DivisionID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DivisionShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisionID");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.EmployeeInformation", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Association")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfMarriage")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesignationID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistrictOfBirth")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeNameLocal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeePhoto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeSignature")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentTypeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FatherNameLocal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FatherOccupation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GradeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IDentificationMark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IsLineSelected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMobileBanking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOTAllowed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseIssueAuthority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseIssuePlace")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LineID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocalAreaClerance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocalAreaRemarks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MembershipCardNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MembershipType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("MembershipValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotherNameLocal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MotherOccupation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldEmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PassportExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportIssueAuthority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PassportIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassportIssuePlace")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PermanentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PreviousEmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProximityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProximityNumber");

                    b.Property<string>("ReferenceAddress1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceAddress2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceName1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceName2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceOccupation1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferenceOccupation2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferencePhone1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ReferencePhone2")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ReferenceRelation1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferenceRelation2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RetirementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryAtJoining")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalaryGradeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalaryStepID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceLength")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShiftEmployeeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpouseBloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SpouseDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpouseOccupation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WeeklyHoliDay")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DesignationID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("EmploymentTypeID");

                    b.HasIndex("GradeID");

                    b.HasIndex("LineID");

                    b.HasIndex("SalaryGradeID");

                    b.HasIndex("SalaryStepID");

                    b.HasIndex("SectionID");

                    b.HasIndex("ShiftEmployeeID");

                    b.HasIndex("UnitID");

                    b.ToTable("EmployeeInformations");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LateApproval", b =>
                {
                    b.Property<string>("LateApprovalID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LateReason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LateApprovalID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LateApprovals");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveApproval", b =>
                {
                    b.Property<string>("LeaveApprovalID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeInformationsEmployeeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeaveEnjoyed")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("LeaveFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveTypeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProvidedLeave")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TotalLeave")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("LeaveApprovalID");

                    b.HasIndex("EmployeeInformationsEmployeeID");

                    b.HasIndex("LeaveTypeID");

                    b.ToTable("LeaveApprovals");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveRecord", b =>
                {
                    b.Property<string>("LeaveRecordID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveEnjoyed")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("LeaveTypeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TotalLeave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaveRecordID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("LeaveTypeID");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveType", b =>
                {
                    b.Property<string>("LeaveTypeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LeaveTypeID");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LineInformation", b =>
                {
                    b.Property<string>("LineID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivisionID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectionsID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitID")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LineID");

                    b.HasIndex("BuildingID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("SectionsID");

                    b.HasIndex("UnitID");

                    b.ToTable("LineInformations");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ManualAttendance", b =>
                {
                    b.Property<string>("ManualAttendanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<string>("AttendanceTime")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OutTime")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ManualAttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ManualAttendances");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.NightAllowance", b =>
                {
                    b.Property<string>("NightAllowanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NightAllowanceRate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaryMaximum")
                        .HasColumnType("money");

                    b.Property<decimal>("SalaryMinimum")
                        .HasColumnType("money");

                    b.HasKey("NightAllowanceID");

                    b.HasIndex("EmploymentTypeID");

                    b.ToTable("NightAllowances");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.NightAllowanceTime", b =>
                {
                    b.Property<string>("NightAllowanceTimeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AllowanceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmploymentTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NightHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NightMinutes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NightAllowanceTimeID");

                    b.HasIndex("EmploymentTypeID");

                    b.ToTable("NightAllowanceTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.OverTime", b =>
                {
                    b.Property<string>("OverTimeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OTDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("OTEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OTStartTime")
                        .HasColumnType("time");

                    b.HasKey("OverTimeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("OverTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ProximityRecord", b =>
                {
                    b.Property<string>("ProximityRecordID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("InTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OutTime")
                        .HasColumnType("time");

                    b.Property<string>("ProximityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProximityRecordID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ProximityRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Sections", b =>
                {
                    b.Property<string>("SectionsID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionNameNative")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SectionShortName")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("SectionsID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ShiftEmployee", b =>
                {
                    b.Property<string>("ShiftEmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DateWiseOfficeTimeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftEmployeeID");

                    b.HasIndex("DateWiseOfficeTimeID");

                    b.ToTable("ShiftEmployees");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ShiftTime", b =>
                {
                    b.Property<string>("ShiftID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BreakDuration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ConsideredLunchHour")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ShiftTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.TiffinAllowanceRate", b =>
                {
                    b.Property<string>("TiffinAllowanceRateID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesignationID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RateInTaka")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TiffinAllowanceRateID");

                    b.HasIndex("DesignationID");

                    b.ToTable("TiffinAllowanceRates");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.TiffinAllowanceTime", b =>
                {
                    b.Property<string>("TiffinAllowanceID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("AllowanceDate")
                        .HasColumnType("date");

                    b.Property<string>("AllowanceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmploymentTypeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("TiffinAllowanceID");

                    b.HasIndex("EmploymentTypeID");

                    b.ToTable("TiffinAllowanceTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Unit", b =>
                {
                    b.Property<string>("UnitID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UnitID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.AttendanceBonus", b =>
                {
                    b.Property<string>("AttendanceBonusID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("BonusCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AttendanceBonusID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AttendanceBonus");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.EmployeeBenefits", b =>
                {
                    b.Property<string>("BenefitID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ApprovalDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BenefitActivationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("BenefitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BenefitDate")
                        .HasColumnType("date");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CashIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntryUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocalAreaClerance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocalAreaRemarks")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("LunchAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewNetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousNetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalaryStepID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("BenefitID");

                    b.ToTable("EmployeeBenefits");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryGrade", b =>
                {
                    b.Property<string>("SalaryGradeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GradeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaryGradeID");

                    b.HasIndex("GradeID");

                    b.ToTable("SalaryGrades");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryRecord", b =>
                {
                    b.Property<string>("SalaryRecordID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Absenteeism")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ActualGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Arrear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AttendanceBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ByBankAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ByCashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DepartmentID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("FoodCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoliDayBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LunchAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LunchBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MobileAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MobileBanking")
                        .HasColumnType("bit");

                    b.Property<int>("MonthDays")
                        .HasColumnType("int");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NightBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OTHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OTRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAllowances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PunchDays")
                        .HasColumnType("int");

                    b.Property<decimal>("SalaryAdvance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SalaryEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalaryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SalaryStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalaryStepID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SpecialAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpecialBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiffinAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalHoliDay")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeave")
                        .HasColumnType("int");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("int");

                    b.HasKey("SalaryRecordID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SalaryStepID");

                    b.ToTable("SalaryRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryStep", b =>
                {
                    b.Property<string>("SalaryStepID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GradeID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HouseAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LunchAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("StepStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaryStepID");

                    b.HasIndex("GradeID");

                    b.ToTable("SalarySteps");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SpecialEmployee", b =>
                {
                    b.Property<string>("SpecialEmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AttendanceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeInformationsEmployeeID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("SpecialEmployeeID");

                    b.HasIndex("EmployeeInformationsEmployeeID");

                    b.ToTable("SpecialEmployees");
                });

            modelBuilder.Entity("HRIS_R62.Models.Second_Phase.EarlyLeaveInformation", b =>
                {
                    b.Property<string>("EarlyLeaveInformationID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("LeaveTime")
                        .HasColumnType("time");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EarlyLeaveInformationID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("EarlyLeaveInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Second_Phase.Grade", b =>
                {
                    b.Property<string>("GradeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConveyanceAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FromGrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GradeShortID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LunchAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Medical")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ToGrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GradeID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceRecord", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.AttendanceConfiguration", null)
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AttendanceConfigurationID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.AttendanceStatus", "AttendanceStatus")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AttendanceStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceStatus");

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Building", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany("Buildings")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.DateWiseOfficeTime", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("DateWiseOfficeTimes")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Department", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.EmployeeInformation", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Department", "Department")
                        .WithMany("EmployeeInformation")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Designation", "Designation")
                        .WithMany("EmployeeInformation")
                        .HasForeignKey("DesignationID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID");

                    b.HasOne("EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeID");

                    b.HasOne("HRIS_R62.Models.Second_Phase.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.LineInformation", "LineInformation")
                        .WithMany()
                        .HasForeignKey("LineID");

                    b.HasOne("HRIS_R62.Models.For_Future.SalaryGrade", "SalaryGrade")
                        .WithMany("EmployeeInformation")
                        .HasForeignKey("SalaryGradeID");

                    b.HasOne("HRIS_R62.Models.For_Future.SalaryStep", "SalaryStep")
                        .WithMany("EmployeeInformations")
                        .HasForeignKey("SalaryStepID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Sections", "Section")
                        .WithMany()
                        .HasForeignKey("SectionID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.ShiftEmployee", "ShiftEmployee")
                        .WithMany()
                        .HasForeignKey("ShiftEmployeeID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Division");

                    b.Navigation("EmploymentType");

                    b.Navigation("Grade");

                    b.Navigation("LineInformation");

                    b.Navigation("SalaryGrade");

                    b.Navigation("SalaryStep");

                    b.Navigation("Section");

                    b.Navigation("ShiftEmployee");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LateApproval", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("LateApprovals")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveApproval", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformations")
                        .WithMany("LeaveApprovals")
                        .HasForeignKey("EmployeeInformationsEmployeeID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.LeaveType", "LeaveType")
                        .WithMany("LeaveApprovals")
                        .HasForeignKey("LeaveTypeID");

                    b.Navigation("EmployeeInformations");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveRecord", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("LeaveRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRIS_R62.Models.Attendance_Required.LeaveType", "LeaveType")
                        .WithMany("LeaveRecords")
                        .HasForeignKey("LeaveTypeID");

                    b.Navigation("EmployeeInformation");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LineInformation", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany("LineInformations")
                        .HasForeignKey("CompanyID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Division", "Division")
                        .WithMany("LineInformation")
                        .HasForeignKey("DivisionID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Sections", "Sections")
                        .WithMany()
                        .HasForeignKey("SectionsID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitID");

                    b.Navigation("Building");

                    b.Navigation("Company");

                    b.Navigation("Division");

                    b.Navigation("Sections");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ManualAttendance", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("ManualAttendances")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.NightAllowance", b =>
                {
                    b.HasOne("EmploymentType", "EmployeeType")
                        .WithMany("NightAllowances")
                        .HasForeignKey("EmploymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.NightAllowanceTime", b =>
                {
                    b.HasOne("EmploymentType", "EmployeeType")
                        .WithMany("NightAllowancesTime")
                        .HasForeignKey("EmploymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.OverTime", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("OverTimes")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ProximityRecord", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Sections", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany("Sectionss")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ShiftEmployee", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.DateWiseOfficeTime", "DateWiseOfficeTime")
                        .WithMany("ShiftEmployees")
                        .HasForeignKey("DateWiseOfficeTimeID");

                    b.Navigation("DateWiseOfficeTime");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.ShiftTime", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("ShiftTimes")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.TiffinAllowanceRate", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Designation", "Designation")
                        .WithMany("TiffinAllowanceRates")
                        .HasForeignKey("DesignationID");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.TiffinAllowanceTime", b =>
                {
                    b.HasOne("EmploymentType", "EmployeeType")
                        .WithMany("TiffinAllowanceTimes")
                        .HasForeignKey("EmploymentTypeID");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Unit", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Company", "Company")
                        .WithMany("Units")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.AttendanceBonus", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("AttendanceBonuses")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryGrade", b =>
                {
                    b.HasOne("HRIS_R62.Models.Second_Phase.Grade", "Grade")
                        .WithMany("SalaryGrades")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryRecord", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.Department", null)
                        .WithMany("SalaryRecords")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRIS_R62.Models.For_Future.SalaryStep", "SalaryStep")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("SalaryStepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");

                    b.Navigation("SalaryStep");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryStep", b =>
                {
                    b.HasOne("HRIS_R62.Models.Second_Phase.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SpecialEmployee", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformations")
                        .WithMany()
                        .HasForeignKey("EmployeeInformationsEmployeeID");

                    b.Navigation("EmployeeInformations");
                });

            modelBuilder.Entity("HRIS_R62.Models.Second_Phase.EarlyLeaveInformation", b =>
                {
                    b.HasOne("HRIS_R62.Models.Attendance_Required.EmployeeInformation", "EmployeeInformation")
                        .WithMany("EarlyLeaveInformations")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("EmploymentType", b =>
                {
                    b.Navigation("NightAllowances");

                    b.Navigation("NightAllowancesTime");

                    b.Navigation("TiffinAllowanceTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceConfiguration", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.AttendanceStatus", b =>
                {
                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Company", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Departments");

                    b.Navigation("LineInformations");

                    b.Navigation("Sectionss");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.DateWiseOfficeTime", b =>
                {
                    b.Navigation("ShiftEmployees");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Department", b =>
                {
                    b.Navigation("EmployeeInformation");

                    b.Navigation("SalaryRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Designation", b =>
                {
                    b.Navigation("EmployeeInformation");

                    b.Navigation("TiffinAllowanceRates");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.Division", b =>
                {
                    b.Navigation("LineInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.EmployeeInformation", b =>
                {
                    b.Navigation("AttendanceBonuses");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("DateWiseOfficeTimes");

                    b.Navigation("EarlyLeaveInformations");

                    b.Navigation("LateApprovals");

                    b.Navigation("LeaveApprovals");

                    b.Navigation("LeaveRecords");

                    b.Navigation("ManualAttendances");

                    b.Navigation("OverTimes");

                    b.Navigation("SalaryRecords");

                    b.Navigation("ShiftTimes");
                });

            modelBuilder.Entity("HRIS_R62.Models.Attendance_Required.LeaveType", b =>
                {
                    b.Navigation("LeaveApprovals");

                    b.Navigation("LeaveRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryGrade", b =>
                {
                    b.Navigation("EmployeeInformation");
                });

            modelBuilder.Entity("HRIS_R62.Models.For_Future.SalaryStep", b =>
                {
                    b.Navigation("EmployeeInformations");

                    b.Navigation("SalaryRecords");
                });

            modelBuilder.Entity("HRIS_R62.Models.Second_Phase.Grade", b =>
                {
                    b.Navigation("SalaryGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
